package com.moltobene.app.ui.theme

import androidx.compose.ui.graphics.Color

// Farbpalette „Schiefer“ (vom Projektinhaber gewählt, siehe Issue #34).
// Ruhiges Blaugrau, damit die Fotos der Gerichte die Farbe tragen.
// Im Code nie diese Werte direkt verwenden, sondern immer MaterialTheme.colorScheme.

// Hell
val SlatePrimaryLight = Color(0xFF3E5A6E)
val SlateOnPrimaryLight = Color(0xFFFFFFFF)
val SlatePrimaryContainerLight = Color(0xFFDCE5EC)
val SlateOnPrimaryContainerLight = Color(0xFF152635)
val SlateSecondaryLight = Color(0xFF545F68)
val SlateOnSecondaryLight = Color(0xFFFFFFFF)
val SlateSecondaryContainerLight = Color(0xFFD8E3EC)
val SlateOnSecondaryContainerLight = Color(0xFF111D25)
val SlateTertiaryLight = Color(0xFF6B5B4E)
val SlateOnTertiaryLight = Color(0xFFFFFFFF)
val SlateTertiaryContainerLight = Color(0xFFF4DFCF)
val SlateOnTertiaryContainerLight = Color(0xFF25190F)
val SlateErrorLight = Color(0xFFBA1A1A)
val SlateOnErrorLight = Color(0xFFFFFFFF)
val SlateErrorContainerLight = Color(0xFFFFDAD6)
val SlateOnErrorContainerLight = Color(0xFF410002)
val SlateBackgroundLight = Color(0xFFF7F8F9)
val SlateOnBackgroundLight = Color(0xFF191C1F)
val SlateSurfaceVariantLight = Color(0xFFDDE3E8)
val SlateOnSurfaceVariantLight = Color(0xFF41484D)
val SlateOutlineLight = Color(0xFF71787E)
val SlateOutlineVariantLight = Color(0xFFC1C7CE)
val SlateInverseSurfaceLight = Color(0xFF2E3134)
val SlateInverseOnSurfaceLight = Color(0xFFEFF1F3)
val SlateSurfaceDimLight = Color(0xFFD7DADD)
val SlateSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SlateSurfaceContainerLowLight = Color(0xFFF1F3F5)
val SlateSurfaceContainerLight = Color(0xFFEBEEF0)
val SlateSurfaceContainerHighLight = Color(0xFFE5E8EB)
val SlateSurfaceContainerHighestLight = Color(0xFFDFE3E6)

// Dunkel
val SlatePrimaryDark = Color(0xFFA9C6DB)
val SlateOnPrimaryDark = Color(0xFF13303F)
val SlatePrimaryContainerDark = Color(0xFF2E4556)
val SlateOnPrimaryContainerDark = Color(0xFFCDE5F7)
val SlateSecondaryDark = Color(0xFFBCC7D0)
val SlateOnSecondaryDark = Color(0xFF26313A)
val SlateSecondaryContainerDark = Color(0xFF3C4750)
val SlateOnSecondaryContainerDark = Color(0xFFD8E3EC)
val SlateTertiaryDark = Color(0xFFD8C3B3)
val SlateOnTertiaryDark = Color(0xFF3B2D22)
val SlateTertiaryContainerDark = Color(0xFF534337)
val SlateOnTertiaryContainerDark = Color(0xFFF4DFCF)
val SlateErrorDark = Color(0xFFFFB4AB)
val SlateOnErrorDark = Color(0xFF690005)
val SlateErrorContainerDark = Color(0xFF93000A)
val SlateOnErrorContainerDark = Color(0xFFFFDAD6)
val SlateBackgroundDark = Color(0xFF121518)
val SlateOnBackgroundDark = Color(0xFFE1E6EA)
val SlateSurfaceVariantDark = Color(0xFF41484D)
val SlateOnSurfaceVariantDark = Color(0xFFC1C7CE)
val SlateOutlineDark = Color(0xFF8B9298)
val SlateOutlineVariantDark = Color(0xFF41484D)
val SlateInverseSurfaceDark = Color(0xFFE1E6EA)
val SlateInverseOnSurfaceDark = Color(0xFF2E3134)
val SlateSurfaceBrightDark = Color(0xFF373B3F)
val SlateSurfaceContainerLowestDark = Color(0xFF0D1013)
val SlateSurfaceContainerLowDark = Color(0xFF1A1D20)
val SlateSurfaceContainerDark = Color(0xFF1C2126)
val SlateSurfaceContainerHighDark = Color(0xFF272B2F)
val SlateSurfaceContainerHighestDark = Color(0xFF32363A)

// Markenfarbe aus dem Logo (Kobaltblau, 08.10.2026): nur für „M“ und „B“ im Schriftzug MOLTOBENE.
// Im Dunkelmodus heller, damit der Kontrast reicht (hell 6,6 : 1, dunkel 7,8 : 1). Im Code über MoltobeneTheme.brand.
val BrandBlueLight = Color(0xFF2747D9)
val BrandBlueDark = Color(0xFF8FA4FF)
