package com.moltobene.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.moltobene.app.data.Palette

/*
 * Farbwelten zur Auswahl in den Einstellungen (vom Projektinhaber am 08.10.2026 gewählt), je hell und dunkel.
 * Eigene Paletten statt der Farben vom Hintergrundbild (Vision: eigene ruhige Farbpalette). Die neuen Farbwelten
 * sind aus „Schiefer“ abgeleitet: gleiche Helligkeit jeder Farbe (HCT-Ton), nur Farbton und Sättigung gedreht –
 * so bleiben alle Kontraste genau wie bei „Schiefer“ (geprüft in PalettesTest). Im Code nie diese Werte direkt
 * verwenden, sondern immer MaterialTheme.colorScheme.
 */

/** Farben einer Farbwelt für Hell oder Dunkel. */
fun colorSchemeOf(palette: Palette, dark: Boolean): ColorScheme = when (palette) {
    Palette.SLATE -> if (dark) SlateDark else SlateLight
    Palette.COBALT -> if (dark) CobaltDark else CobaltLight
    Palette.SAGE -> if (dark) SageDark else SageLight
    Palette.TERRACOTTA -> if (dark) TerracottaDark else TerracottaLight
    Palette.SAFFRON -> if (dark) SaffronDark else SaffronLight
}

// „Schiefer“: ruhiges Blaugrau, der Standard (Werte in Color.kt).
internal val SlateLight = lightColorScheme(
    primary = SlatePrimaryLight,
    onPrimary = SlateOnPrimaryLight,
    primaryContainer = SlatePrimaryContainerLight,
    onPrimaryContainer = SlateOnPrimaryContainerLight,
    inversePrimary = SlatePrimaryDark,
    secondary = SlateSecondaryLight,
    onSecondary = SlateOnSecondaryLight,
    secondaryContainer = SlateSecondaryContainerLight,
    onSecondaryContainer = SlateOnSecondaryContainerLight,
    tertiary = SlateTertiaryLight,
    onTertiary = SlateOnTertiaryLight,
    tertiaryContainer = SlateTertiaryContainerLight,
    onTertiaryContainer = SlateOnTertiaryContainerLight,
    error = SlateErrorLight,
    onError = SlateOnErrorLight,
    errorContainer = SlateErrorContainerLight,
    onErrorContainer = SlateOnErrorContainerLight,
    background = SlateBackgroundLight,
    onBackground = SlateOnBackgroundLight,
    surface = SlateBackgroundLight,
    onSurface = SlateOnBackgroundLight,
    surfaceVariant = SlateSurfaceVariantLight,
    onSurfaceVariant = SlateOnSurfaceVariantLight,
    surfaceTint = SlatePrimaryLight,
    outline = SlateOutlineLight,
    outlineVariant = SlateOutlineVariantLight,
    inverseSurface = SlateInverseSurfaceLight,
    inverseOnSurface = SlateInverseOnSurfaceLight,
    surfaceBright = SlateBackgroundLight,
    surfaceDim = SlateSurfaceDimLight,
    surfaceContainerLowest = SlateSurfaceContainerLowestLight,
    surfaceContainerLow = SlateSurfaceContainerLowLight,
    surfaceContainer = SlateSurfaceContainerLight,
    surfaceContainerHigh = SlateSurfaceContainerHighLight,
    surfaceContainerHighest = SlateSurfaceContainerHighestLight,
)

internal val SlateDark = darkColorScheme(
    primary = SlatePrimaryDark,
    onPrimary = SlateOnPrimaryDark,
    primaryContainer = SlatePrimaryContainerDark,
    onPrimaryContainer = SlateOnPrimaryContainerDark,
    inversePrimary = SlatePrimaryLight,
    secondary = SlateSecondaryDark,
    onSecondary = SlateOnSecondaryDark,
    secondaryContainer = SlateSecondaryContainerDark,
    onSecondaryContainer = SlateOnSecondaryContainerDark,
    tertiary = SlateTertiaryDark,
    onTertiary = SlateOnTertiaryDark,
    tertiaryContainer = SlateTertiaryContainerDark,
    onTertiaryContainer = SlateOnTertiaryContainerDark,
    error = SlateErrorDark,
    onError = SlateOnErrorDark,
    errorContainer = SlateErrorContainerDark,
    onErrorContainer = SlateOnErrorContainerDark,
    background = SlateBackgroundDark,
    onBackground = SlateOnBackgroundDark,
    surface = SlateBackgroundDark,
    onSurface = SlateOnBackgroundDark,
    surfaceVariant = SlateSurfaceVariantDark,
    onSurfaceVariant = SlateOnSurfaceVariantDark,
    surfaceTint = SlatePrimaryDark,
    outline = SlateOutlineDark,
    outlineVariant = SlateOutlineVariantDark,
    inverseSurface = SlateInverseSurfaceDark,
    inverseOnSurface = SlateInverseOnSurfaceDark,
    surfaceBright = SlateSurfaceBrightDark,
    surfaceDim = SlateBackgroundDark,
    surfaceContainerLowest = SlateSurfaceContainerLowestDark,
    surfaceContainerLow = SlateSurfaceContainerLowDark,
    surfaceContainer = SlateSurfaceContainerDark,
    surfaceContainerHigh = SlateSurfaceContainerHighDark,
    surfaceContainerHighest = SlateSurfaceContainerHighestDark,
)

// „Kobalt“: Das Blau des App-Symbols, etwas ruhiger.
internal val CobaltLight = lightColorScheme(
    primary = Color(0xFF4050A4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDCE3FF),
    onPrimaryContainer = Color(0xFF1D1C58),
    secondary = Color(0xFF555C7F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDAE0FF),
    onSecondaryContainer = Color(0xFF11193B),
    tertiary = Color(0xFF675E36),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFEEE3B3),
    onTertiaryContainer = Color(0xFF221B00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF9F7FB),
    onBackground = Color(0xFF1B1B20),
    surface = Color(0xFFF9F7FB),
    onSurface = Color(0xFF1B1B20),
    surfaceVariant = Color(0xFFE2E1EB),
    onSurfaceVariant = Color(0xFF45474F),
    outline = Color(0xFF767680),
    outlineVariant = Color(0xFFC7C5D0),
    inverseSurface = Color(0xFF303035),
    inverseOnSurface = Color(0xFFF1F0F5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F2F7),
    surfaceContainer = Color(0xFFEEEDF2),
    surfaceContainerHigh = Color(0xFFE8E7ED),
    surfaceContainerHighest = Color(0xFFE2E2E8),
    inversePrimary = Color(0xFFB1BFFF),
    surfaceTint = Color(0xFF4050A4),
    surfaceBright = Color(0xFFF9F7FB),
    surfaceDim = Color(0xFFDAD9DF),
)

internal val CobaltDark = darkColorScheme(
    primary = Color(0xFFB1BFFF),
    onPrimary = Color(0xFF052670),
    primaryContainer = Color(0xFF313C83),
    onPrimaryContainer = Color(0xFFDBE0FF),
    secondary = Color(0xFFBCC4E9),
    onSecondary = Color(0xFF282D50),
    secondaryContainer = Color(0xFF3E4367),
    onSecondaryContainer = Color(0xFFDAE0FF),
    tertiary = Color(0xFFD3C796),
    onTertiary = Color(0xFF382F0A),
    tertiaryContainer = Color(0xFF50461E),
    onTertiaryContainer = Color(0xFFEEE3B3),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF141419),
    onBackground = Color(0xFFE5E5EC),
    surface = Color(0xFF141419),
    onSurface = Color(0xFFE5E5EC),
    surfaceVariant = Color(0xFF45474F),
    onSurfaceVariant = Color(0xFFC7C5D0),
    outline = Color(0xFF90909A),
    outlineVariant = Color(0xFF45474F),
    inverseSurface = Color(0xFFE5E5EC),
    inverseOnSurface = Color(0xFF303035),
    surfaceContainerLowest = Color(0xFF0F0F14),
    surfaceContainerLow = Color(0xFF1C1C21),
    surfaceContainer = Color(0xFF202027),
    surfaceContainerHigh = Color(0xFF2A2A30),
    surfaceContainerHighest = Color(0xFF35353B),
    inversePrimary = Color(0xFF4050A4),
    surfaceTint = Color(0xFFB1BFFF),
    surfaceBright = Color(0xFF3A3A40),
    surfaceDim = Color(0xFF141419),
)

// „Salbei“: gedämpftes Kräutergrün.
internal val SageLight = lightColorScheme(
    primary = Color(0xFF4B5C3B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE3E6D3),
    onPrimaryContainer = Color(0xFF192815),
    secondary = Color(0xFF59604F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDFE4CF),
    onSecondaryContainer = Color(0xFF171E10),
    tertiary = Color(0xFF645B66),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFEBDFEB),
    onTertiaryContainer = Color(0xFF1F1923),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFBF8F0),
    onBackground = Color(0xFF1A1D18),
    surface = Color(0xFFFBF8F0),
    onSurface = Color(0xFF1A1D18),
    surfaceVariant = Color(0xFFE2E3D5),
    onSurfaceVariant = Color(0xFF45483D),
    outline = Color(0xFF75796C),
    outlineVariant = Color(0xFFC4C8BA),
    inverseSurface = Color(0xFF2F312C),
    inverseOnSurface = Color(0xFFF3F1E8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F3EA),
    surfaceContainer = Color(0xFFF0EEE3),
    surfaceContainerHigh = Color(0xFFE9E8DE),
    surfaceContainerHighest = Color(0xFFE4E3D7),
    inversePrimary = Color(0xFFB7C89F),
    surfaceTint = Color(0xFF4B5C3B),
    surfaceBright = Color(0xFFFBF8F0),
    surfaceDim = Color(0xFFDBDAD0),
)

internal val SageDark = darkColorScheme(
    primary = Color(0xFFB7C89F),
    onPrimary = Color(0xFF253114),
    primaryContainer = Color(0xFF38472C),
    onPrimaryContainer = Color(0xFFD9E7C2),
    secondary = Color(0xFFC2C8B4),
    onSecondary = Color(0xFF2A3224),
    secondaryContainer = Color(0xFF404838),
    onSecondaryContainer = Color(0xFFDFE4CF),
    tertiary = Color(0xFFCFC3D0),
    onTertiary = Color(0xFF342D38),
    tertiaryContainer = Color(0xFF4B434F),
    onTertiaryContainer = Color(0xFFEBDFEB),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF131611),
    onBackground = Color(0xFFE6E6D9),
    surface = Color(0xFF131611),
    onSurface = Color(0xFFE6E6D9),
    surfaceVariant = Color(0xFF45483D),
    onSurfaceVariant = Color(0xFFC4C8BA),
    outline = Color(0xFF8F9385),
    outlineVariant = Color(0xFF45483D),
    inverseSurface = Color(0xFFE6E6D9),
    inverseOnSurface = Color(0xFF2F312C),
    surfaceContainerLowest = Color(0xFF0E110C),
    surfaceContainerLow = Color(0xFF1B1E18),
    surfaceContainer = Color(0xFF1D221A),
    surfaceContainerHigh = Color(0xFF282C25),
    surfaceContainerHighest = Color(0xFF333730),
    inversePrimary = Color(0xFF4B5C3B),
    surfaceTint = Color(0xFFB7C89F),
    surfaceBright = Color(0xFF383C34),
    surfaceDim = Color(0xFF131611),
)

// „Terrakotta“: warmes Tonrot.
internal val TerracottaLight = lightColorScheme(
    primary = Color(0xFF864522),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCD1),
    onPrimaryContainer = Color(0xFF3E1B00),
    secondary = Color(0xFF7A5544),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDACC),
    onSecondaryContainer = Color(0xFF2F1407),
    tertiary = Color(0xFF4C616B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD1E6F1),
    onTertiaryContainer = Color(0xFF051E27),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF6F5),
    onBackground = Color(0xFF211A17),
    surface = Color(0xFFFFF6F5),
    onSurface = Color(0xFF211A17),
    surfaceVariant = Color(0xFFF3DED8),
    onSurfaceVariant = Color(0xFF53443E),
    outline = Color(0xFF85736C),
    outlineVariant = Color(0xFFD7C2B9),
    inverseSurface = Color(0xFF372F2B),
    inverseOnSurface = Color(0xFFFCEEEB),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFEF0ED),
    surfaceContainer = Color(0xFFFAEAE8),
    surfaceContainerHigh = Color(0xFFF4E4E0),
    surfaceContainerHighest = Color(0xFFF0DFDB),
    inversePrimary = Color(0xFFFFAF8D),
    surfaceTint = Color(0xFF864522),
    surfaceBright = Color(0xFFFFF6F5),
    surfaceDim = Color(0xFFE6D6D2),
)

internal val TerracottaDark = darkColorScheme(
    primary = Color(0xFFFFAF8D),
    onPrimary = Color(0xFF501D07),
    primaryContainer = Color(0xFF693415),
    onPrimaryContainer = Color(0xFFFFDACC),
    secondary = Color(0xFFEABBA9),
    onSecondary = Color(0xFF472817),
    secondaryContainer = Color(0xFF603E2C),
    onSecondaryContainer = Color(0xFFFFDACC),
    tertiary = Color(0xFFB4CAD6),
    onTertiary = Color(0xFF1C333C),
    tertiaryContainer = Color(0xFF324A53),
    onTertiaryContainer = Color(0xFFD1E6F1),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1310),
    onBackground = Color(0xFFF5E1DC),
    surface = Color(0xFF1A1310),
    onSurface = Color(0xFFF5E1DC),
    surfaceVariant = Color(0xFF53443E),
    onSurfaceVariant = Color(0xFFD7C2B9),
    outline = Color(0xFFA08D86),
    outlineVariant = Color(0xFF53443E),
    inverseSurface = Color(0xFFF5E1DC),
    inverseOnSurface = Color(0xFF372F2B),
    surfaceContainerLowest = Color(0xFF150E0B),
    surfaceContainerLow = Color(0xFF221B17),
    surfaceContainer = Color(0xFF291E18),
    surfaceContainerHigh = Color(0xFF322924),
    surfaceContainerHighest = Color(0xFF3E332E),
    inversePrimary = Color(0xFF864522),
    surfaceTint = Color(0xFFFFAF8D),
    surfaceBright = Color(0xFF433833),
    surfaceDim = Color(0xFF1A1310),
)

// „Safran“: warmes Senfgelb, hell eher Ocker.
internal val SaffronLight = lightColorScheme(
    primary = Color(0xFF705200),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFAE0BD),
    onPrimaryContainer = Color(0xFF2E2300),
    secondary = Color(0xFF6E5B37),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF9DEB4),
    onSecondaryContainer = Color(0xFF261900),
    tertiary = Color(0xFF565E71),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDCE2F8),
    onTertiaryContainer = Color(0xFF121B2C),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF6F2),
    onBackground = Color(0xFF1F1B15),
    surface = Color(0xFFFFF6F2),
    onSurface = Color(0xFF1F1B15),
    surfaceVariant = Color(0xFFEEE0D1),
    onSurfaceVariant = Color(0xFF4F4639),
    outline = Color(0xFF807667),
    outlineVariant = Color(0xFFD0C5B4),
    inverseSurface = Color(0xFF343029),
    inverseOnSurface = Color(0xFFFAEFE6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFCF1E8),
    surfaceContainer = Color(0xFFF8EBE2),
    surfaceContainerHigh = Color(0xFFF1E6DB),
    surfaceContainerHighest = Color(0xFFEDE0D5),
    inversePrimary = Color(0xFFE9BB67),
    surfaceTint = Color(0xFF705200),
    surfaceBright = Color(0xFFFFF6F2),
    surfaceDim = Color(0xFFE3D8CE),
)

internal val SaffronDark = darkColorScheme(
    primary = Color(0xFFE9BB67),
    onPrimary = Color(0xFF3E2900),
    primaryContainer = Color(0xFF563F00),
    onPrimaryContainer = Color(0xFFFFDDA5),
    secondary = Color(0xFFDCC29A),
    onSecondary = Color(0xFF3C2E0B),
    secondaryContainer = Color(0xFF544321),
    onSecondaryContainer = Color(0xFFF9DEB4),
    tertiary = Color(0xFFBFC6DD),
    onTertiary = Color(0xFF273042),
    tertiaryContainer = Color(0xFF3D4659),
    onTertiaryContainer = Color(0xFFDCE2F8),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF17140E),
    onBackground = Color(0xFFF1E3D6),
    surface = Color(0xFF17140E),
    onSurface = Color(0xFFF1E3D6),
    surfaceVariant = Color(0xFF4F4639),
    onSurfaceVariant = Color(0xFFD0C5B4),
    outline = Color(0xFF9B9080),
    outlineVariant = Color(0xFF4F4639),
    inverseSurface = Color(0xFFF1E3D6),
    inverseOnSurface = Color(0xFF343029),
    surfaceContainerLowest = Color(0xFF120F09),
    surfaceContainerLow = Color(0xFF201C16),
    surfaceContainer = Color(0xFF242016),
    surfaceContainerHigh = Color(0xFF2F2A21),
    surfaceContainerHighest = Color(0xFF3A352C),
    inversePrimary = Color(0xFF705200),
    surfaceTint = Color(0xFFE9BB67),
    surfaceBright = Color(0xFF3F3A31),
    surfaceDim = Color(0xFF17140E),
)
